version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - ./backend:/app
    restart: always

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    volumes:
      - ./frontend:/app
    restart: always

  nginx:
    image: nginx:stable-alpine
    depends_on:
      - backend
      - frontend
    ports:
      - "6969:80"
    volumes:
      # Use the NGINX config
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      # Serve React files
      - ./frontend/dist:/usr/share/nginx/html
    restart: always
